version: 2
jobs:
  install:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
  build:
    docker:
        - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            - dependencies-
      - run: yarn run build
      - run:
          name : Persist
          command: |
            cp -r ./dist /tmp/server

      - persist_to_workspace:
          root: ~/
          paths:
            - tmp/server

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  deploy:
    docker:
        - image: circleci/node:dubnium-browsers
    working_directory: ~/deploy-doc-server
    steps:
        - attach_workspace:
            at: /tmp
        - run:
            name: Deploy app
            command: |
                npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir /tmp/server-doc --prod



workflows:
    version: 2
    front-install:
      jobs:
        - install
        - build:
            requires:
                - install
        - deploy:
            requires:
                - build
